TIER2_CITIES = {
    "agra",
    "aligarh",
    "allahabad",
    "prayagraj",
    "amritsar",
    "bareilly",
    "mysuru",
    "hubli-dharwad",
    "hubballi",
    "jalandhar",
    "jodhpur",
    "ludhiana",
    "meerut",
    "moradabad",
    "udaipur",
    "varanasi",
    "belagavi",
    "mangaluru",
    "kochi",
    "kozhikode",
    "thiruvananthapuram",
    "tiruchirappalli",
    "warangal",
    "coimbatore",
    "madurai",
    "asansol",
    "dhanbad",
    "durgapur",
    "patna",
    "raipur",
    "ranchi",
    "visakhapatnam",
    "vijayawada",
    "aurangabad",
    "rajkot",
    "nashik",
    "faridabad",
    "ghaziabad",
    "jaipur",
    "kanpur",
    "lucknow",
    "nagpur",
    "bhopal",
    "gwalior",
    "indore",
    "jabalpur",
    "bhubaneswar",
    "surat",
    "vadodara",
    "dehradun",
    "guwahati",
}


def is_tier2_city(city: str) -> bool:
    return city.strip().lower() in TIER2_CITIES
